name: Android CI (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Install the platform + build-tools that match the project
      - name: Install Android platforms & build-tools
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-33" \
                     "build-tools;33.0.1"

      # Gradle cache (uses system Gradle, NOT ./gradlew)
      - name: Set up Gradle 8.x (cache)
        uses: gradle/actions/setup-gradle@v3

      # ⬇️ IMPORTANT: set the folder that contains `settings.gradle` or `settings.gradle.kts`
      # If your Gradle project is at the repo root, use '.'.
      # If it's inside a folder (e.g. 'project'), change PATH_TO_PROJECT to that folder name.
      - name: Build Debug APK
        working-directory: PATH_TO_PROJECT
        run: gradle assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: SalesMaster-debug
          path: PATH_TO_PROJECT/app/build/outputs/apk/debug/*.apk
